#ifndef FT4FT8UTILITIES_H_
#define FT4FT8UTILITIES_H_
/*
 *      FT4FT8Utilities.h - FT4 FT8 Utilities
 *
 *      Copyright (C) 2024
 *          Mark Broihier
 *
 */

/* ---------------------------------------------------------------------- */
#include <stdint.h>
#include <map>
#include <vector>
#include <cstdio>
#include <cstdlib>
static const std::vector<bool> ldpc_generator[83] =
  { { true, false, false, false, false, false, true, true,
      false, false, true, false, true, false, false, true,
      true, true, false, false, true, true, true, false,
      false, false, false, true, false, false, false, true,
      true, false, true, true, true, true, true, true,
      false, false, true, true, false, false, false, true,
      true, true, true, false, true, false, true, false,
      true, true, true, true, false, true, false, true,
      false, false, false, false, true, false, false, true,
      true, true, true, true, false, false, true, false,
      false, true, true, true, true, true, true, true,
      true, true, false, false },
    { false, true, true, true, false, true, true, false,
      false, false, false, true, true, true, false, false,
      false, false, true, false, false, true, true, false,
      false, true, false, false, true, true, true, false,
      false, false, true, false, false, true, false, true,
      true, true, false, false, false, false, true, false,
      false, true, false, true, true, false, false, true,
      false, false, true, true, false, false, true, true,
      false, true, false, true, false, true, false, false,
      true, false, false, true, false, false, true, true,
      false, false, false, true, false, false, true, true,
      false, false, true, false },
    { true, true, false, true, true, true, false, false,
      false, false, true, false, false, true, true, false,
      false, true, false, true, true, false, false, true,
      false, false, false, false, false, false, true, false,
      true, true, true, true, true, false, true, true,
      false, false, true, false, false, true, true, true,
      false, true, true, true, true, true, false, false,
      false, true, true, false, false, true, false, false,
      false, false, false, true, false, false, false, false,
      true, false, true, false, false, false, false, true,
      true, false, true, true, true, true, false, true,
      true, true, false, false },
    { false, false, false, true, true, false, true, true,
      false, false, true, true, true, true, true, true,
      false, true, false, false, false, false, false, true,
      false, true, true, true, true, false, false, false,
      false, true, false, true, true, false, false, false,
      true, true, false, false, true, true, false, true,
      false, false, true, false, true, true, false, true,
      true, true, false, true, false, false, true, true,
      false, false, true, true, true, true, true, false,
      true, true, false, false, false, true, true, true,
      true, true, true, true, false, true, true, false,
      false, false, true, false },
    { false, false, false, false, true, false, false, true,
      true, true, true, true, true, true, false, true,
      true, false, true, false, false, true, false, false,
      true, true, true, true, true, true, true, false,
      true, true, true, false, false, false, false, false,
      false, true, false, false, false, false, false, true,
      true, false, false, true, false, true, false, true,
      true, true, true, true, true, true, false, true,
      false, false, false, false, false, false, true, true,
      false, true, false, false, false, true, true, true,
      true, false, false, false, false, false, true, true,
      true, false, true, false },
    { false, false, false, false, false, true, true, true,
      false, true, true, true, true, true, false, false,
      true, true, false, false, true, true, false, false,
      true, true, false, false, false, false, false, true,
      false, false, false, true, true, false, true, true,
      true, false, false, false, true, false, false, false,
      false, true, true, true, false, false, true, true,
      true, true, true, false, true, true, false, true,
      false, true, false, true, true, true, false, false,
      false, false, true, true, true, true, false, true,
      false, true, false, false, true, false, false, false,
      true, false, true, false },
    { false, false, true, false, true, false, false, true,
      true, false, true, true, false, true, true, false,
      false, false, true, false, true, false, true, false,
      true, true, true, true, true, true, true, false,
      false, false, true, true, true, true, false, false,
      true, false, true, false, false, false, false, false,
      false, false, true, true, false, true, true, false,
      true, true, true, true, false, true, false, false,
      true, true, true, true, true, true, true, false,
      false, false, false, true, true, false, true, false,
      true, false, false, true, true, true, false, true,
      true, false, true, false },
    { false, true, true, false, false, false, false, false,
      false, true, false, true, false, true, false, false,
      true, true, true, true, true, false, true, false,
      true, true, true, true, false, true, false, true,
      true, true, true, true, false, false, true, true,
      false, true, false, true, true, true, false, true,
      true, false, false, true, false, true, true, false,
      true, true, false, true, false, false, true, true,
      true, false, true, true, false, false, false, false,
      true, true, false, false, true, false, false, false,
      true, true, false, false, false, false, true, true,
      true, true, true, false },
    { true, true, true, false, false, false, true, false,
      false, false, false, false, false, true, true, true,
      true, false, false, true, true, false, false, false,
      true, true, true, false, false, true, false, false,
      false, false, true, true, false, false, false, true,
      false, false, false, false, true, true, true, false,
      true, true, true, false, true, true, false, true,
      false, false, true, false, false, true, true, true,
      true, false, false, false, true, false, false, false,
      false, true, false, false, true, false, true, false,
      true, true, true, false, true, false, false, true,
      false, false, false, false },
    { false, true, true, true, false, true, true, true,
      false, true, false, true, true, true, false, false,
      true, false, false, true, true, true, false, false,
      false, false, false, false, true, false, false, false,
      true, true, true, false, true, false, false, false,
      false, false, false, false, true, true, true, false,
      false, false, true, false, false, true, true, false,
      true, true, false, true, true, true, false, true,
      true, false, true, false, true, true, true, false,
      false, true, false, true, false, true, true, false,
      false, false, true, true, false, false, false, true,
      true, false, false, false },
    { true, false, true, true, false, false, false, false,
      true, false, true, true, true, false, false, false,
      false, false, false, true, false, false, false, true,
      false, false, false, false, false, false, true, false,
      true, false, false, false, true, true, false, false,
      false, false, true, false, true, false, true, true,
      true, true, true, true, true, false, false, true,
      true, false, false, true, false, true, true, true,
      false, false, true, false, false, false, false, true,
      false, false, true, true, false, true, false, false,
      true, false, false, false, false, true, true, true,
      true, true, false, false },
    { false, false, false, true, true, false, false, false,
      true, false, true, false, false, false, false, false,
      true, true, false, false, true, false, false, true,
      false, false, true, false, false, false, true, true,
      false, false, false, true, true, true, true, true,
      true, true, false, false, false, true, true, false,
      false, false, false, false, true, false, true, false,
      true, true, false, true, true, true, true, true,
      false, true, false, true, true, true, false, false,
      false, true, false, true, true, true, true, false,
      true, false, true, false, false, false, true, true,
      false, false, true, false },
    { false, true, true, true, false, true, true, false,
      false, true, false, false, false, true, true, true,
      false, false, false, true, true, true, true, false,
      true, false, false, false, false, false, true, true,
      false, false, false, false, false, false, true, false,
      true, false, true, false, false, false, false, false,
      false, true, true, true, false, false, true, false,
      false, false, false, true, true, true, true, false,
      false, false, false, false, false, false, false, true,
      true, false, true, true, false, false, false, true,
      false, false, true, false, true, false, true, true,
      true, false, false, false },
    { true, true, true, true, true, true, true, true,
      true, false, true, true, true, true, false, false,
      true, true, false, false, true, false, true, true,
      true, false, false, false, false, false, false, false,
      true, true, false, false, true, false, true, false,
      true, false, false, false, false, false, true, true,
      false, true, false, false, false, false, false, true,
      true, true, true, true, true, false, true, false,
      true, true, true, true, true, false, true, true,
      false, true, false, false, false, true, true, true,
      true, false, true, true, false, false, true, false,
      true, true, true, false },
    { false, true, true, false, false, true, true, false,
      true, false, true, false, false, true, true, true,
      false, false, true, false, true, false, true, false,
      false, false, false, true, false, true, false, true,
      true, false, false, false, true, true, true, true,
      true, false, false, true, false, false, true, true,
      false, false, true, false, false, true, false, true,
      true, false, true, false, false, false, true, false,
      true, false, true, true, true, true, true, true,
      false, true, true, false, false, true, true, true,
      false, false, false, true, false, true, true, true,
      false, false, false, false },
    { true, true, false, false, false, true, false, false,
      false, false, true, false, false, true, false, false,
      false, false, true, true, false, true, true, false,
      true, false, false, false, true, false, false, true,
      true, true, true, true, true, true, true, false,
      true, false, false, false, false, true, false, true,
      true, false, true, true, false, false, false, true,
      true, true, false, false, false, true, false, true,
      false, false, false, true, false, false, true, true,
      false, true, true, false, false, false, true, true,
      true, false, true, false, false, false, false, true,
      true, false, false, false },
    { false, false, false, false, true, true, false, true,
      true, true, true, true, true, true, true, true,
      false, true, true, true, false, false, true, true,
      true, false, false, true, false, true, false, false,
      false, false, false, true, false, true, false, false,
      true, true, false, true, false, false, false, true,
      true, false, true, false, false, false, false, true,
      true, false, true, true, false, false, true, true,
      false, true, false, false, true, false, true, true,
      false, false, false, true, true, true, false, false,
      false, false, true, false, false, true, true, true,
      false, false, false, false },
    { false, false, false, true, false, true, false, true,
      true, false, true, true, false, true, false, false,
      true, false, false, false, true, false, false, false,
      false, false, true, true, false, false, false, false,
      false, true, true, false, false, false, true, true,
      false, true, true, false, true, true, false, false,
      true, false, false, false, true, false, true, true,
      true, false, false, true, true, false, false, true,
      true, false, false, false, true, false, false, true,
      false, true, false, false, true, false, false, true,
      false, true, true, true, false, false, true, false,
      true, true, true, false },
    { false, false, true, false, true, false, false, true,
      true, false, true, false, true, false, false, false,
      true, false, false, true, true, true, false, false,
      false, false, false, false, true, true, false, true,
      false, false, true, true, true, true, false, true,
      true, true, true, false, true, false, false, false,
      false, false, false, true, true, true, false, true,
      false, true, true, false, false, true, true, false,
      false, true, false, true, false, true, false, false,
      true, false, false, false, true, false, false, true,
      true, false, true, true, false, false, false, false,
      true, true, true, false },
    { false, true, false, false, true, true, true, true,
      false, false, false, true, false, false, true, false,
      false, true, true, false, true, true, true, true,
      false, false, true, true, false, true, true, true,
      true, true, true, true, true, false, true, false,
      false, true, false, true, false, false, false, true,
      true, true, false, false, true, false, true, true,
      true, true, true, false, false, true, true, false,
      false, false, false, true, true, false, true, true,
      true, true, false, true, false, true, true, false,
      true, false, true, true, true, false, false, true,
      false, true, false, false },
    { true, false, false, true, true, false, false, true,
      true, true, false, false, false, true, false, false,
      false, true, true, true, false, false, true, false,
      false, false, true, true, true, false, false, true,
      true, true, false, true, false, false, false, false,
      true, true, false, true, true, false, false, true,
      false, true, true, true, true, true, false, true,
      false, false, true, true, true, true, false, false,
      true, false, false, false, false, true, false, false,
      true, true, true, false, false, false, false, false,
      true, false, false, true, false, true, false, false,
      false, false, false, false },
    { false, false, false, true, true, false, false, true,
      false, false, false, true, true, false, false, true,
      true, false, true, true, false, true, true, true,
      false, true, false, true, false, false, false, true,
      false, false, false, true, true, false, false, true,
      false, true, true, true, false, true, true, false,
      false, true, false, true, false, true, true, false,
      false, false, true, false, false, false, false, true,
      true, false, true, true, true, false, true, true,
      false, true, false, false, true, true, true, true,
      false, false, false, true, true, true, true, false,
      true, false, false, false },
    { false, false, false, false, true, false, false, true,
      true, true, false, true, true, false, true, true,
      false, false, false, true, false, false, true, false,
      true, true, false, true, false, true, true, true,
      false, false, true, true, false, false, false, true,
      true, true, true, true, true, false, true, false,
      true, true, true, false, true, true, true, false,
      false, false, false, false, true, false, true, true,
      true, false, false, false, false, true, true, false,
      true, true, false, true, true, true, true, true,
      false, true, true, false, true, false, true, true,
      true, false, false, false },
    { false, true, false, false, true, false, false, false,
      true, false, false, false, true, true, true, true,
      true, true, false, false, false, false, true, true,
      false, false, true, true, true, true, false, true,
      true, true, true, true, false, true, false, false,
      false, false, true, true, true, true, true, true,
      true, false, true, true, true, true, false, true,
      true, true, true, false, true, true, true, false,
      true, false, true, false, false, true, false, false,
      true, true, true, false, true, false, true, false,
      true, true, true, true, true, false, true, true,
      false, true, false, false },
    { true, false, false, false, false, false, true, false,
      false, true, true, true, false, true, false, false,
      false, false, true, false, false, false, true, true,
      true, true, true, false, true, true, true, false,
      false, true, false, false, false, false, false, false,
      true, false, true, true, false, true, true, false,
      false, true, true, true, false, true, false, true,
      true, true, true, true, false, true, true, true,
      false, true, false, true, false, true, true, false,
      true, true, true, false, true, false, true, true,
      false, true, false, true, true, true, true, true,
      true, true, true, false },
    { true, false, true, false, true, false, true, true,
      true, true, true, false, false, false, false, true,
      true, false, false, true, false, true, true, true,
      true, true, false, false, false, true, false, false,
      true, false, false, false, false, true, false, false,
      true, true, false, false, true, false, true, true,
      false, true, true, true, false, true, false, false,
      false, true, true, true, false, true, false, true,
      false, true, true, true, false, false, false, true,
      false, true, false, false, false, true, false, false,
      true, false, true, false, true, false, false, true,
      true, false, true, false },
    { false, false, true, false, true, false, true, true,
      false, true, false, true, false, false, false, false,
      false, false, false, false, true, true, true, false,
      false, true, false, false, true, false, true, true,
      true, true, false, false, false, false, false, false,
      true, true, true, false, true, true, false, false,
      false, true, false, true, true, false, true, false,
      false, true, true, false, true, true, false, true,
      false, false, true, false, true, false, true, true,
      true, true, false, true, true, false, true, true,
      true, true, false, true, true, true, false, true,
      false, false, false, false },
    { true, true, false, false, false, true, false, false,
      false, true, true, true, false, true, false, false,
      true, false, true, false, true, false, true, false,
      false, true, false, true, false, false, true, true,
      true, true, false, true, false, true, true, true,
      false, false, false, false, false, false, true, false,
      false, false, false, true, true, false, false, false,
      false, true, true, true, false, true, true, false,
      false, false, false, true, false, true, true, false,
      false, true, true, false, true, false, false, true,
      false, false, true, true, false, true, true, false,
      false, false, false, false },
    { true, false, false, false, true, true, true, false,
      true, false, true, true, true, false, true, false,
      false, false, false, true, true, false, true, false,
      false, false, false, true, false, false, true, true,
      true, true, false, true, true, false, true, true,
      false, false, true, true, false, false, true, true,
      true, false, false, true, false, false, false, false,
      true, false, true, true, true, true, false, true,
      false, true, true, false, false, true, true, true,
      false, false, false, true, true, false, false, false,
      true, true, false, false, true, true, true, false,
      true, true, false, false },
    { false, true, true, true, false, true, false, true,
      false, false, true, true, true, false, false, false,
      false, true, false, false, false, true, false, false,
      false, true, true, false, false, true, true, true,
      false, false, true, true, true, false, true, false,
      false, false, true, false, false, true, true, true,
      false, true, true, true, true, false, false, false,
      false, false, true, false, true, true, false, false,
      true, true, false, false, false, true, false, false,
      false, false, true, false, false, false, false, false,
      false, false, false, true, false, false, true, false,
      true, true, true, false },
    { false, false, false, false, false, true, true, false,
      true, true, true, true, true, true, true, true,
      true, false, false, false, false, false, true, true,
      true, false, true, false, false, false, false, true,
      false, true, false, false, false, true, false, true,
      true, true, false, false, false, false, true, true,
      false, true, true, true, false, false, false, false,
      false, false, true, true, false, true, false, true,
      true, false, true, false, false, true, false, true,
      true, true, false, false, false, false, false, true,
      false, false, true, false, false, true, true, false,
      true, false, false, false },
    { false, false, true, true, true, false, true, true,
      false, false, true, true, false, true, true, true,
      false, true, false, false, false, false, false, true,
      false, true, true, true, true, false, false, false,
      false, true, false, true, true, false, false, false,
      true, true, false, false, true, true, false, false,
      false, false, true, false, true, true, false, true,
      true, true, false, true, false, false, true, true,
      false, false, true, true, true, true, true, false,
      true, true, false, false, false, false, true, true,
      true, true, true, true, false, true, true, false,
      false, false, true, false },
    { true, false, false, true, true, false, true, false,
      false, true, false, false, true, false, true, false,
      false, true, false, true, true, false, true, false,
      false, false, true, false, true, false, false, false,
      true, true, true, false, true, true, true, false,
      false, false, false, true, false, true, true, true,
      true, true, false, false, true, false, true, false,
      true, false, false, true, true, true, false, false,
      false, false, true, true, false, false, true, false,
      false, true, false, false, true, false, false, false,
      false, true, false, false, false, false, true, false,
      true, true, false, false },
    { true, false, true, true, true, true, false, false,
      false, false, true, false, true, false, false, true,
      true, true, true, true, false, true, false, false,
      false, true, true, false, false, true, false, true,
      false, false, true, true, false, false, false, false,
      true, false, false, true, true, true, false, false,
      true, false, false, true, false, true, true, true,
      false, true, true, true, true, true, true, false,
      true, false, false, false, true, false, false, true,
      false, true, true, false, false, false, false, true,
      false, false, false, false, true, false, true, false,
      false, true, false, false },
    { false, false, true, false, false, true, true, false,
      false, true, true, false, false, false, true, true,
      true, false, true, false, true, true, true, false,
      false, true, true, false, true, true, false, true,
      true, true, false, true, true, true, true, true,
      true, false, false, false, true, false, true, true,
      false, true, false, true, true, true, false, false,
      true, true, true, false, false, false, true, false,
      true, false, true, true, true, false, true, true,
      false, false, true, false, true, false, false, true,
      false, true, false, false, true, false, false, false,
      true, false, false, false },
    { false, true, false, false, false, true, true, false,
      true, true, true, true, false, false, true, false,
      false, false, true, true, false, false, false, true,
      true, true, true, false, true, true, true, true,
      true, true, true, false, false, true, false, false,
      false, true, false, true, false, true, true, true,
      false, false, false, false, false, false, true, true,
      false, true, false, false, true, true, false, false,
      false, false, false, true, true, false, false, false,
      false, false, false, true, false, true, false, false,
      false, true, false, false, false, false, false, true,
      true, false, false, false },
    { false, false, true, true, true, true, true, true,
      true, false, true, true, false, false, true, false,
      true, true, false, false, true, true, true, false,
      true, false, false, false, false, true, false, true,
      true, false, true, false, true, false, true, true,
      true, true, true, false, true, false, false, true,
      true, false, true, true, false, false, false, false,
      true, true, false, false, false, true, true, true,
      false, false, true, false, true, true, true, false,
      false, false, false, false, false, true, true, false,
      true, true, true, true, true, false, true, true,
      true, true, true, false },
    { true, true, false, true, true, true, true, false,
      true, false, false, false, false, true, true, true,
      false, true, false, false, true, false, false, false,
      false, false, false, true, true, true, true, true,
      false, false, true, false, true, false, false, false,
      false, false, true, false, true, true, false, false,
      false, false, false, true, false, true, false, true,
      false, false, true, true, true, false, false, true,
      false, true, true, true, false, false, false, true,
      true, false, true, false, false, false, false, false,
      true, false, true, false, false, false, true, false,
      true, true, true, false },
    { true, true, true, true, true, true, false, false,
      true, true, false, true, false, true, true, true,
      true, true, false, false, true, true, false, false,
      true, true, true, true, false, false, true, false,
      false, false, true, true, true, true, false, false,
      false, true, true, false, true, false, false, true,
      true, true, true, true, true, false, true, false,
      true, false, false, true, true, false, false, true,
      true, false, true, true, true, false, true, true,
      true, false, true, false, false, false, false, true,
      false, true, false, false, false, false, false, true,
      false, false, true, false },
    { true, true, true, true, false, false, false, false,
      false, false, true, false, false, true, true, false,
      false, false, false, true, false, true, false, false,
      false, true, false, false, false, true, true, true,
      true, true, true, false, true, false, false, true,
      false, true, false, false, true, false, false, true,
      false, false, false, false, true, true, false, false,
      true, false, true, false, true, false, false, false,
      true, true, true, false, false, true, false, false,
      false, true, true, true, false, true, false, false,
      true, true, false, false, true, true, true, false,
      true, true, false, false },
    { false, true, false, false, false, true, false, false,
      false, false, false, true, false, false, false, false,
      false, false, false, true, false, false, false, true,
      false, true, false, true, true, false, false, false,
      false, false, false, true, true, false, false, false,
      false, false, false, true, true, false, false, true,
      false, true, true, false, true, true, true, true,
      true, false, false, true, false, true, false, true,
      true, true, false, false, true, true, false, true,
      true, true, false, true, false, true, true, true,
      false, false, false, false, false, false, false, true,
      false, false, true, false },
    { false, false, false, false, true, false, false, false,
      true, false, false, false, true, true, true, true,
      true, true, false, false, false, false, true, true,
      false, false, false, true, true, true, false, true,
      true, true, true, true, false, true, false, false,
      true, false, true, true, true, true, true, true,
      true, false, true, true, true, true, false, true,
      true, true, true, false, false, false, true, false,
      true, false, true, false, false, true, false, false,
      true, true, true, false, true, false, true, false,
      true, true, true, true, true, false, true, true,
      false, true, false, false },
    { true, false, true, true, true, false, false, false,
      true, true, true, true, true, true, true, false,
      true, true, true, true, false, false, false, true,
      true, false, true, true, false, true, true, false,
      false, false, true, true, false, false, false, false,
      false, true, true, true, false, true, true, true,
      false, false, true, false, true, false, false, true,
      true, true, true, true, true, false, true, true,
      false, false, false, false, true, false, true, false,
      false, false, false, false, false, true, true, true,
      true, false, false, false, true, true, false, false,
      false, false, false, false },
    { false, true, false, true, true, false, true, false,
      true, true, true, true, true, true, true, false,
      true, false, true, false, false, true, true, true,
      true, false, true, false, true, true, false, false,
      true, true, false, false, true, true, false, false,
      true, false, true, true, false, true, true, true,
      false, true, true, true, true, false, true, true,
      true, false, true, true, true, true, false, false,
      true, false, false, true, true, true, false, true,
      true, false, false, true, true, false, false, true,
      true, false, true, false, true, false, false, true,
      false, false, false, false },
    { false, true, false, false, true, false, false, true,
      true, false, true, false, false, true, true, true,
      false, false, false, false, false, false, false, true,
      false, true, true, false, true, false, true, false,
      true, true, false, false, false, true, true, false,
      false, true, false, true, false, false, true, true,
      true, true, true, true, false, true, true, false,
      false, true, false, true, true, true, true, false,
      true, true, false, false, true, true, false, true,
      true, true, false, false, true, false, false, true,
      false, false, false, false, false, true, true, true,
      false, true, true, false },
    { false, false, false, true, true, false, false, true,
      false, true, false, false, false, true, false, false,
      true, true, false, true, false, false, false, false,
      true, false, false, false, false, true, false, true,
      true, false, true, true, true, true, true, false,
      false, true, false, false, true, true, true, false,
      false, true, true, true, true, true, false, true,
      true, false, true, false, true, false, false, false,
      true, true, false, true, false, true, true, false,
      true, true, false, false, true, true, false, false,
      false, true, true, true, true, true, false, true,
      false, false, false, false },
    { false, false, true, false, false, true, false, true,
      false, false, false, true, true, true, true, true,
      false, true, true, false, false, false, true, false,
      true, false, true, false, true, true, false, true,
      true, true, false, false, false, true, false, false,
      false, false, false, false, false, false, true, true,
      false, false, true, false, true, true, true, true,
      false, false, false, false, true, true, true, false,
      true, true, true, false, false, true, true, true,
      false, false, false, true, false, true, false, false,
      false, false, false, false, false, false, false, false,
      false, false, true, false },
    { false, true, false, true, false, true, true, false,
      false, true, false, false, false, true, true, true,
      false, false, false, true, true, true, true, true,
      true, false, false, false, false, true, true, true,
      false, false, false, false, false, false, true, false,
      true, false, true, false, false, false, false, false,
      false, true, true, true, false, false, true, false,
      false, false, false, true, true, true, true, false,
      false, false, false, false, false, false, false, false,
      true, false, true, true, false, false, false, true,
      false, false, true, false, true, false, true, true,
      true, false, false, false },
    { false, false, true, false, true, false, true, true,
      true, false, false, false, true, true, true, false,
      false, true, false, false, true, false, false, true,
      false, false, true, false, false, false, true, true,
      true, true, true, true, false, false, true, false,
      true, true, false, true, true, true, false, true,
      false, true, false, true, false, false, false, true,
      true, true, true, false, false, false, true, false,
      true, true, false, true, false, true, false, true,
      false, false, true, true, false, true, true, true,
      true, true, true, true, true, false, true, false,
      false, false, false, false },
    { false, true, true, false, true, false, true, true,
      false, true, false, true, false, true, false, true,
      false, false, false, false, true, false, true, false,
      false, true, false, false, false, false, false, false,
      true, false, true, false, false, true, true, false,
      false, true, true, false, true, true, true, true,
      false, true, false, false, false, true, true, true,
      false, true, false, true, false, true, false, true,
      true, true, false, true, true, true, true, false,
      true, false, false, true, false, true, false, true,
      true, true, false, false, false, false, true, false,
      false, true, true, false },
    { true, false, true, false, false, false, false, true,
      true, false, false, false, true, false, true, false,
      true, true, false, true, false, false, true, false,
      true, false, false, false, true, true, false, true,
      false, true, false, false, true, true, true, false,
      false, false, true, false, false, true, true, true,
      true, true, true, true, true, true, true, false,
      true, false, false, true, false, false, true, false,
      true, false, true, false, false, true, false, false,
      true, true, true, true, false, true, true, false,
      true, true, false, false, true, false, false, false,
      false, true, false, false },
    { false, false, false, true, false, false, false, false,
      true, true, false, false, false, false, true, false,
      true, true, true, false, false, true, false, true,
      true, false, false, false, false, true, true, false,
      false, false, true, true, true, false, false, false,
      true, false, false, false, true, true, false, false,
      true, false, true, true, true, false, false, false,
      false, false, true, false, true, false, true, false,
      false, false, true, true, true, true, false, true,
      true, false, false, false, false, false, false, false,
      false, true, true, true, false, true, false, true,
      true, false, false, false },
    { true, true, true, false, true, true, true, true,
      false, false, true, true, false, true, false, false,
      true, false, true, false, false, true, false, false,
      false, false, false, true, true, false, false, false,
      false, false, false, true, false, true, true, true,
      true, true, true, false, true, true, true, false,
      false, false, false, false, false, false, true, false,
      false, false, false, true, false, false, true, true,
      false, false, true, true, true, true, false, true,
      true, false, true, true, false, false, true, false,
      true, true, true, false, true, false, true, true,
      false, false, false, false },
    { false, true, true, true, true, true, true, false,
      true, false, false, true, true, true, false, false,
      false, false, false, false, true, true, false, false,
      false, true, false, true, false, true, false, false,
      false, false, true, true, false, false, true, false,
      false, true, false, true, true, false, true, false,
      true, false, false, true, true, true, false, false,
      false, false, false, true, false, true, false, true,
      true, false, false, false, false, false, true, true,
      false, true, true, false, true, true, true, false,
      false, false, false, false, false, false, false, false,
      false, false, false, false },
    { false, false, true, true, false, true, true, false,
      true, false, false, true, false, false, true, true,
      true, true, true, false, false, true, false, true,
      false, true, true, true, false, false, true, false,
      true, true, false, true, false, false, false, true,
      true, true, true, true, true, true, false, true,
      true, true, true, false, false, true, false, false,
      true, true, false, false, true, true, false, true,
      true, true, true, true, false, false, false, false,
      false, true, true, true, true, false, false, true,
      true, true, true, false, true, false, false, false,
      false, true, true, false },
    { true, false, true, true, true, true, true, true,
      true, false, true, true, false, false, true, false,
      true, true, false, false, true, true, true, false,
      true, true, false, false, false, true, false, true,
      true, false, true, false, true, false, true, true,
      true, true, true, false, false, false, false, true,
      true, false, true, true, false, false, false, false,
      true, true, false, false, false, true, true, true,
      false, false, true, false, true, true, true, false,
      false, false, false, false, false, true, true, true,
      true, true, true, true, true, false, true, true,
      true, true, true, false },
    { false, true, true, true, true, true, true, false,
      true, true, true, false, false, false, false, true,
      true, false, false, false, false, false, true, false,
      false, false, true, true, false, false, false, false,
      true, true, false, false, false, true, false, true,
      true, false, false, false, false, false, true, true,
      true, true, false, false, true, true, false, false,
      true, true, false, false, true, true, false, false,
      false, true, false, true, false, true, true, true,
      true, true, false, true, false, true, false, false,
      true, false, true, true, false, false, false, false,
      true, false, false, false },
    { true, false, true, false, false, false, false, false,
      false, true, true, false, false, true, true, false,
      true, true, false, false, true, false, true, true,
      false, false, true, false, true, true, true, true,
      true, true, true, false, true, true, false, true,
      true, false, true, false, true, true, true, true,
      true, true, false, false, true, false, false, true,
      true, true, true, true, false, true, false, true,
      false, false, true, false, false, true, true, false,
      false, true, true, false, false, true, false, false,
      false, false, false, true, false, false, true, false,
      false, true, true, false },
    { true, false, true, true, true, false, true, true,
      false, false, true, false, false, false, true, true,
      false, true, true, true, false, false, true, false,
      false, true, false, true, true, false, true, false,
      true, false, true, true, true, true, false, false,
      false, true, false, false, false, true, true, true,
      true, true, false, false, true, true, false, false,
      false, true, false, true, true, true, true, true,
      false, true, false, false, true, true, false, false,
      true, true, false, false, false, true, false, false,
      true, true, false, false, true, true, false, true,
      false, false, true, false },
    { true, true, false, true, true, true, true, false,
      true, true, false, true, true, false, false, true,
      true, true, false, true, true, false, true, true,
      true, false, true, false, false, false, true, true,
      true, false, true, true, true, true, true, false,
      true, true, true, false, false, true, false, false,
      false, false, false, false, true, true, false, false,
      false, true, false, true, true, false, false, true,
      true, false, true, true, false, true, false, true,
      false, true, true, false, false, false, false, false,
      true, false, false, true, true, false, true, true,
      false, true, false, false },
    { true, true, false, true, true, false, false, true,
      true, false, true, false, false, true, true, true,
      false, false, false, false, false, false, false, true,
      false, true, true, false, true, false, true, false,
      true, true, false, false, false, true, true, false,
      false, true, false, true, false, false, true, true,
      true, true, true, false, false, true, true, false,
      true, true, false, true, true, true, true, false,
      true, true, false, false, true, true, false, true,
      true, true, false, false, true, false, false, true,
      false, false, false, false, false, false, true, true,
      false, true, true, false },
    { true, false, false, true, true, false, true, false,
      true, true, false, true, false, true, false, false,
      false, true, true, false, true, false, true, false,
      true, true, true, false, true, true, false, true,
      false, true, false, true, true, true, true, true,
      false, true, true, true, false, false, false, false,
      false, true, true, true, true, true, true, true,
      false, false, true, false, true, false, false, false,
      false, false, false, false, true, false, true, false,
      true, false, true, true, false, true, false, true,
      true, true, true, true, true, true, false, false,
      false, true, false, false },
    { true, true, true, false, false, true, false, true,
      true, false, false, true, false, false, true, false,
      false, false, false, true, true, true, false, false,
      false, true, true, true, false, true, true, true,
      true, false, false, false, false, false, true, false,
      false, false, true, false, false, true, false, true,
      true, false, false, false, false, true, true, true,
      false, false, true, true, false, false, false, true,
      false, true, true, false, true, true, false, true,
      false, true, true, true, true, true, false, true,
      false, false, true, true, true, true, false, false,
      false, false, true, false },
    { false, true, false, false, true, true, true, true,
      false, false, false, true, false, true, false, false,
      true, true, false, true, true, false, true, false,
      true, false, false, false, false, false, true, false,
      false, true, false, false, false, false, true, false,
      true, false, true, false, true, false, false, false,
      true, false, true, true, true, false, false, false,
      false, true, true, false, true, true, false, true,
      true, true, false, false, true, false, true, false,
      false, true, true, true, false, false, true, true,
      false, false, true, true, false, true, false, true,
      false, false, true, false },
    { true, false, false, false, true, false, true, true,
      true, false, false, false, true, false, true, true,
      false, true, false, true, false, false, false, false,
      false, true, true, true, true, false, true, false,
      true, true, false, true, false, true, false, false,
      false, true, true, false, false, true, true, true,
      true, true, false, true, false, true, false, false,
      false, true, false, false, false, true, false, false,
      false, false, false, true, true, true, false, true,
      true, true, true, true, false, true, true, true,
      false, true, true, true, false, false, false, false,
      true, true, true, false },
    { false, false, true, false, false, false, true, false,
      true, false, false, false, false, false, true, true,
      false, false, false, true, true, true, false, false,
      true, false, false, true, true, true, false, false,
      true, true, true, true, false, false, false, true,
      false, false, false, true, false, true, true, false,
      true, false, false, true, false, true, false, false,
      false, true, true, false, false, true, true, true,
      true, false, true, false, true, true, false, true,
      false, false, false, false, false, true, false, false,
      true, false, true, true, false, true, true, false,
      true, false, false, false },
    { false, false, true, false, false, false, false, true,
      false, false, true, true, true, false, true, true,
      true, false, false, false, false, false, true, true,
      true, false, false, false, true, true, true, true,
      true, true, true, false, false, false, true, false,
      true, false, true, false, true, true, true, false,
      false, true, false, true, false, true, false, false,
      true, true, false, false, false, false, true, true,
      true, false, false, false, true, true, true, false,
      true, true, true, false, false, true, true, true,
      false, false, false, true, true, false, false, false,
      false, false, false, false },
    { false, true, false, true, true, true, false, true,
      true, false, false, true, false, false, true, false,
      false, true, true, false, true, false, true, true,
      false, true, true, false, true, true, false, true,
      true, true, false, true, false, true, true, true,
      false, false, false, true, true, true, true, true,
      false, false, false, false, true, false, false, false,
      false, true, false, true, false, false, false, true,
      true, false, false, false, false, false, false, true,
      true, false, true, false, false, true, false, false,
      true, true, true, false, false, false, false, true,
      false, false, true, false },
    { false, true, true, false, false, true, true, false,
      true, false, true, false, true, false, true, true,
      false, true, true, true, true, false, false, true,
      true, true, false, true, false, true, false, false,
      true, false, true, true, false, false, true, false,
      true, false, false, true, true, true, true, false,
      true, true, true, false, false, true, true, false,
      true, true, true, false, false, true, true, false,
      true, false, false, true, false, true, false, true,
      false, false, false, false, true, false, false, true,
      true, true, true, false, false, true, false, true,
      false, true, true, false },
    { true, false, false, true, false, true, false, true,
      true, false, false, false, false, false, false, true,
      false, true, false, false, true, false, false, false,
      false, true, true, false, true, false, false, false,
      false, false, true, false, true, true, false, true,
      false, true, true, true, false, true, false, false,
      true, false, false, false, true, false, true, false,
      false, false, true, true, true, false, false, false,
      true, true, false, true, true, true, false, true,
      false, true, true, false, true, false, false, false,
      true, false, true, true, true, false, true, false,
      true, false, true, false },
    { true, false, true, true, true, false, false, false,
      true, true, false, false, true, true, true, false,
      false, false, false, false, false, false, true, false,
      false, false, false, false, true, true, false, false,
      true, true, true, true, false, false, false, false,
      false, true, true, false, true, false, false, true,
      true, true, false, false, false, false, true, true,
      false, false, true, false, true, false, true, false,
      false, true, true, true, false, false, true, false,
      false, false, true, true, true, false, true, false,
      true, false, true, true, false, false, false, true,
      false, true, false, false },
    { true, true, true, true, false, true, false, false,
      false, false, true, true, false, false, true, true,
      false, false, false, true, true, true, false, true,
      false, true, true, false, true, true, false, true,
      false, true, false, false, false, true, true, false,
      false, false, false, true, false, true, true, false,
      false, false, false, false, false, true, true, true,
      true, true, true, false, true, false, false, true,
      false, true, false, true, false, true, true, true,
      false, true, false, true, false, false, true, false,
      false, true, true, true, false, true, false, false,
      false, true, true, false },
    { false, true, true, false, true, true, false, true,
      true, false, true, false, false, false, true, false,
      false, false, true, true, true, false, true, true,
      true, false, true, false, false, true, false, false,
      false, false, true, false, false, true, false, false,
      true, false, true, true, true, false, false, true,
      false, true, false, true, true, false, false, true,
      false, true, true, false, false, false, false, true,
      false, false, true, true, false, false, true, true,
      true, true, false, false, true, true, true, true,
      true, false, false, true, true, true, false, false,
      true, false, false, false },
    { true, false, true, false, false, true, true, false,
      false, false, true, true, false, true, true, false,
      true, false, true, true, true, true, false, false,
      true, false, true, true, true, true, false, false,
      false, true, true, true, true, false, true, true,
      false, false, true, true, false, false, false, false,
      true, true, false, false, false, true, false, true,
      true, true, true, true, true, false, true, true,
      true, true, true, false, true, false, true, false,
      true, true, true, false, false, true, true, false,
      false, true, true, true, true, true, true, true,
      true, true, true, false },
    { false, true, false, true, true, true, false, false,
      true, false, true, true, false, false, false, false,
      true, true, false, true, true, false, false, false,
      false, true, true, false, true, false, true, false,
      false, false, false, false, false, true, true, true,
      true, true, false, true, true, true, true, true,
      false, true, true, false, false, true, false, true,
      false, true, false, false, true, false, true, false,
      true, false, false, true, false, false, false, false,
      true, false, false, false, true, false, false, true,
      true, false, true, false, false, false, true, false,
      false, false, false, false },
    { true, true, true, true, false, false, false, true,
      false, false, false, true, true, true, true, true,
      false, false, false, true, false, false, false, false,
      false, true, true, false, true, false, false, false,
      false, true, false, false, true, false, false, false,
      false, true, true, true, true, false, false, false,
      false, false, false, false, true, true, true, true,
      true, true, false, false, true, false, false, true,
      true, true, true, false, true, true, false, false,
      true, true, false, true, true, true, false, true,
      true, false, false, false, false, false, false, false,
      true, false, true, false },
    { false, false, false, true, true, true, true, true,
      true, false, true, true, true, false, true, true,
      false, true, false, true, false, false, true, true,
      false, true, true, false, false, true, false, false,
      true, true, true, true, true, false, true, true,
      true, false, false, false, true, true, false, true,
      false, false, true, false, true, true, false, false,
      true, false, false, true, true, true, false, true,
      false, true, true, true, false, false, true, true,
      false, false, false, false, true, true, false, true,
      false, true, false, true, true, false, true, true,
      true, false, true, false },
    { true, true, true, true, true, true, false, false,
      true, false, true, true, true, false, false, false,
      false, true, true, false, true, false, true, true,
      true, true, false, false, false, true, true, true,
      false, false, false, false, true, false, true, false,
      false, true, false, true, false, false, false, false,
      true, true, false, false, true, false, false, true,
      true, true, false, true, false, false, false, false,
      false, false, true, false, true, false, true, false,
      false, true, false, true, true, true, false, true,
      false, false, false, false, false, false, true, true,
      false, true, false, false },
    { true, false, true, false, false, true, false, true,
      false, false, true, true, false, true, false, false,
      false, true, false, false, false, false, true, true,
      false, false, true, true, false, false, false, false,
      false, false, true, false, true, false, false, true,
      true, true, true, false, true, false, true, false,
      true, true, false, false, false, false, false, true,
      false, true, false, true, true, true, true, true,
      false, false, true, true, false, false, true, false,
      false, false, true, false, true, true, true, false,
      false, false, true, true, false, true, false, false,
      true, true, false, false },
    { true, true, false, false, true, false, false, true,
      true, false, false, false, true, false, false, true,
      true, true, false, true, true, false, false, true,
      true, true, false, false, false, true, true, true,
      true, true, false, false, false, false, true, true,
      true, true, false, true, false, false, true, true,
      true, false, true, true, true, false, false, false,
      true, true, false, false, false, true, false, true,
      false, true, false, true, true, true, false, true,
      false, true, true, true, false, true, false, true,
      false, false, false, true, false, false, true, true,
      false, false, false, false },
    { false, true, true, true, true, false, true, true,
      true, false, true, true, false, false, true, true,
      true, false, false, false, true, false, true, true,
      false, false, true, false, true, true, true, true,
      false, false, false, false, false, false, false, true,
      true, false, false, false, false, true, true, false,
      true, true, false, true, false, true, false, false,
      false, true, true, false, false, true, true, false,
      false, true, false, false, false, false, true, true,
      true, false, true, false, true, true, true, false,
      true, false, false, true, false, true, true, false,
      false, false, true, false },
    { false, false, true, false, false, true, true, false,
      false, true, false, false, false, true, false, false,
      true, true, true, false, true, false, true, true,
      true, false, true, false, true, true, false, true,
      true, true, true, false, true, false, true, true,
      false, true, false, false, false, true, false, false,
      true, false, true, true, true, false, false, true,
      false, true, false, false, false, true, true, false,
      false, true, true, true, true, true, false, true,
      false, false, false, true, true, true, true, true,
      false, true, false, false, false, false, true, false,
      true, true, false, false },
    { false, true, true, false, false, false, false, false,
      true, false, false, false, true, true, false, false,
      true, true, false, false, true, false, false, false,
      false, true, false, true, false, true, true, true,
      false, true, false, true, true, false, false, true,
      false, true, false, false, true, false, true, true,
      true, true, true, true, true, false, true, true,
      true, false, true, true, false, true, false, true,
      false, true, false, true, true, true, false, true,
      false, true, true, false, true, false, false, true,
      false, true, true, false, false, false, false, false,
      false, false, false, false }
  };
/* ---------------------------------------------------------------------- */
class FT4FT8Utilities {
 private:
 public:
  FT4FT8Utilities(void) {}
  uint32_t static toGray(uint32_t v) { const uint32_t map[] = {0, 1, 3, 2, 5, 6, 4, 7 }; return map[v]; }
  std::vector<bool> static crc(std::vector<bool> message);
  std::vector<bool> static ldpc(std::vector<bool> message);
  bool static checkLdpc(std::vector<bool> payload, uint32_t index, std::map<uint32_t,
                        std::vector<uint32_t>> * possibleBits);
  bool static fastCheckLdpc(std::vector<bool> payload, uint32_t index);
  uint32_t static scoreLdpc(std::vector<bool> payload, std::map<uint32_t, std::vector<uint32_t>> * possibleBits);
  uint32_t static fastScoreLdpc(std::vector<bool> payload);

  ~FT4FT8Utilities(void) {}
};
#endif  //  FT4FT8UTILITIES_H_
